### ISSUE TITLE
Mongo Cache Error

### ISSUE THREAD

**Issue by fivesmallq** [growthbook/growthbook-proxy#16]
When I use mongo as a cache, if the conditions in the featrue involve expressions such as in list, which require expressions, an error will be reported when the cache is set, and the information is as follows.

```shell
{"level":50,"time":1678091056765,"pid":29,"hostname":"growthbook-proxy-6c8586dfd6-p8s4m","err":{"type":"MongoServerError","message":"The dollar ($) prefixed field '$in' in 'entry.payload.features.demo-feature.rules.0.condition.id.$in' is not valid for storage.","stack":"MongoServerError: The dollar ($) prefixed field '$in' in 'entry.payload.features.demo-feature.rules.0.condition.id.$in' is not valid for storage.\n    at /usr/local/src/app/node_modules/mongodb/lib/operations/update.js:132:33\n    at /usr/local/src/app/node_modules/mongodb/lib/cmap/connection_pool.js:333:25\n    at /usr/local/src/app/node_modules/mongodb/lib/sdam/server.js:212:17\n    at handleOperationResult (/usr/local/src/app/node_modules/mongodb/lib/sdam/server.js:328:20)\n    at Connection.onMessage (/usr/local/src/app/node_modules/mongodb/lib/cmap/connection.js:239:9)\n    at MessageStream.<anonymous> (/usr/local/src/app/node_modules/mongodb/lib/cmap/connection.js:60:60)\n    at MessageStream.emit (node:events:513:28)\n    at processIncomingData (/usr/local/src/app/node_modules/mongodb/lib/cmap/message_stream.js:125:16)\n    at MessageStream._write (/usr/local/src/app/node_modules/mongodb/lib/cmap/message_stream.js:33:9)\n    at writeOrBuffer (node:internal/streams/writable:391:12)","index":0,"code":52,"codeName":"DollarPrefixedFieldName"},"msg":"Unable to refresh stale cache"}
```

```json
{"defaultValue":false,"rules":[{"condition":{"id":{"$in":["1","2","3","4"]}},"force":true},{"condition":{"partnerId":"1"},"force":true}]}
```

**Comment by fivesmallq** [comment]
Another inconvenience is that I am not able to customize the database name. I would like to put the cache collection of the proxy in the growthbook database as well.

**Comment by bryce-fitzsimons** [comment]
Sorry for the slow reply, and thanks for bringing this to my attention. I'll have a look at these issues.

**Comment by bryce-fitzsimons** [comment]
Hi @fivesmallq, I've resolved both of these issues in the latest build (1.0.14).

For customizing your Mongo connection, you now have 2 addtitional env vars:
`CACHE_DATABASE_NAME`
`CACHE_COLLECTION_NAME`

**Comment by fivesmallq** [comment]
Wow, that's amazing! Lightning-fast speed, thank you so much. I will upgrade and test it later.
