### ISSUE TITLE
ERR_INVALID_URL for cloud users

### ISSUE THREAD

**Issue by kma-leovvay** [growthbook/growthbook-proxy#60]
i'm trying to setup a proxy for a cloud instance, with growth_api set to public cloud
```doockerfile
ENV GROWTHBOOK_API_HOST = https://cdn.growthbook.io
```

but i get an error

```
2024-06-26T19:05:40.882 app[683d55df763148] hkg [info] | TypeError: Failed to parse URL from = https://cdn.growthbook.io/api/v1/sdk-connections?withProxy=1&limit=100&offset=0

2024-06-26T19:05:40.882 app[683d55df763148] hkg [info] | at node:internal/deps/undici/undici:12618:11

2024-06-26T19:05:40.882 app[683d55df763148] hkg [info] | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {

2024-06-26T19:05:40.882 app[683d55df763148] hkg [info] | [cause]: TypeError [ERR_INVALID_URL]: Invalid URL

2024-06-26T19:05:40.882 app[683d55df763148] hkg [info] | at new NodeError (node:internal/errors:405:5)

2024-06-26T19:05:40.882 app[683d55df763148] hkg [info] | at new URL (node:internal/url:676:13)

2024-06-26T19:05:40.882 app[683d55df763148] hkg [info] | at new Request (node:internal/deps/undici/undici:6108:25)

2024-06-26T19:05:40.882 app[683d55df763148] hkg [info] | at fetch (node:internal/deps/undici/undici:10396:25)

2024-06-26T19:05:40.882 app[683d55df763148] hkg [info] | at Object.fetch (node:internal/deps/undici/undici:12617:10)

2024-06-26T19:05:40.882 app[683d55df763148] hkg [info] | at fetch (node:internal/process/pre_execution:281:25)

2024-06-26T19:05:40.882 app[683d55df763148] hkg [info] | at Registrar.<anonymous> (/usr/local/src/app/packages/apps/proxy/dist/services/registrar/index.js:108:36)

2024-06-26T19:05:40.882 app[683d55df763148] hkg [info] | at Generator.next (<anonymous>)

2024-06-26T19:05:40.882 app[683d55df763148] hkg [info] | at /usr/local/src/app/packages/apps/proxy/dist/services/registrar/index.js:8:71

2024-06-26T19:05:40.882 app[683d55df763148] hkg [info] | at new Promise (<anonymous>) {

2024-06-26T19:05:40.882 app[683d55df763148] hkg [info] | input: '= https://cdn.growthbook.io/api/v1/sdk-connections?withProxy=1&limit=100&offset=0',

2024-06-26T19:05:40.882 app[683d55df763148] hkg [info] | code: 'ERR_INVALID_URL'
```

**Comment by bryce-fitzsimons** [comment]
This suggests that somehow you're setting your env variable value to `'= https://cdn.growthbook.io'`. Please double check your env vars.
